name: flutter_app
description: A new Flutter project.

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.4
  camera: ^0.10.5+9

